USE qk6vpj34qoyrw4cr;
INSERT INTO Sections
    (section)
VALUES
    ("Entry Lighting"),
    ("Driveway"),
    ("Walkway Around Home"),
    ("Door Steps"),
    ("Garage"),
    ("Ramps"),
    ("Exterior Doors"),
    ("Patio Area(s)"),
    ("Interior: Entry Ways & Vestibules"),
    ("Hallways & Doors"),
    ("Interior Stairs"),
    ("Living/Dining Room"),
    ("Flex Room"),
    ("Master Bedroom");
    -- ("Master Bedroom Closet"),
    -- ("Master Bedroom Safety (Dementia/Children)"),
    -- ("Master Bathroom"),
    -- ("Bedroom #2"),
    -- ("Bedroom #2 Closet"),
    -- ("Bedroom #2 Safety (Dementia/Children)"),
    -- ("Bedroom #2 Bathroom"),
    -- ("Bedroom #3"),
    -- ("Bedroom #3 Closet"),
    -- ("Bedroom #3 Safety (Dementia/Children)"),
    -- ("Bedroom #3 Bathroom"),
    -- ("Kitchen"),
    -- ("Kitchen Safety (Dementia/Children)"),
    -- ("Pantry"),
    -- ("Laundry"),
    -- ("Mud Room"),
    -- ("Hallway Closet"),
    -- ("Storage Room"),
    -- ("Garage"),
    -- ("General Considerations"),
    -- ("Needs Consideration"),
    -- ("Basement");

INSERT INTO Questions
    (question, SectionId)
VALUES

    ("Driveway", 1),
    ("Garage", 1),
    ("Walkways", 1),
    ("All Doors", 1),
    ("Portico/Porch", 1),
    ("Security", 1),
    ("Stairs", 1),

    ("What is the driveway surface condition?", 2),
    ("Is the driveway sloped?", 2),

    ("Are walkways smooth and level (no cracks, gaps or other tripping hazards)?", 3),
    ("Are transitions between different surfaces (a patio and sidewalk, concrete and asphalt, walkway and grass, etc.) even and level?", 3),
    ("If there are steeply inclined walkways, do they have sturdy, easy-to-grasp handrails?", 3),
    ("Are shrubs, bushes and grass trimmed back or removed so they do not infringe on or obstruct the walkway (potential tripping hazard)? ", 3),

    ("Do all steps (even single steps) have sturdy, easy-to-grasp (cylindrical) rails on both sides?", 4),
    ("Are the stairs and multiple steps of equal height?", 4),
    ("Are the stair treads sturdy, level and in good condition?", 4),

    ("Are there adequate overhead lights in the garage? Is there a clear pathway to walk through?", 5),
    ("Do entry stair/s or ramps to the house have railings?", 5),

    ("Are ramps rising at a minimum slope of 12:1 (12 inches of ramp length for every one inch of height is standard. However, 16:1 is recommended.)", 6),
    ("Do ramps have sturdy rails on both sides?", 6),
    ("Are the rails cylindrical for easy grasping?", 6),
    ("Do ramps have smooth transition from ramp surface to ground surface?", 6),
    ("Do ramps have non-skid surfaces or have non-skid strips been added?", 6),
    ("Do ramp railings extend beyond the ramp to help people transition off the ramp?", 6),
    ("Does the ramp have a resting place every 20 ft.? Transition every 30 ft.?", 6),
    ("Is there color contrast for depth perception?", 6),
    ("Is there adequate lighting for way finding?", 6),

    ("Can the door accommodate passage of wheelchairs?", 7),
    ("Is there a deadbolt on the interior of the door?", 7),
    ("Are locks easy to operate?", 7),
    ("Is the door handle, knob, lever, thumb press, and easy to use?", 7),
    ("Do the doors open and close easily without sticking?", 7),
    ("Do doors on springs close slowly enough (so they don't close on someone going through the door)?", 7),
    ("Do glass sliding doors have decals at eye level?", 7),
    ("Are  the doors easy to open?", 7),

    ("If there is a patio or deck, is it level, smoothly surfaced and free of tripping hazards?", 8),
    ("Are garbage and recycling areas well lit?", 8),
    ("Do these areas have safe, accessible stairs and railings on both sides of the stoop or stairs?", 8),
    ("Have working chimneys been professionally inspected and cleaned within the last year?", 8),

    ("Have throw rugs (potential tripping hazards) been removed?", 9),
    ("Is there a clear pathway (devoid of clutter) through the entry hall?", 9),
    ("Are all cords and wires out of the pathway?", 9),
    ("Are thresholds low enough (less than 1/2 in) so someone does not trip over them?", 9),
    ("Is there adequate lighting? ", 9),
    ("Is the light switch at the entrance to the room? ", 9),
    ("lf necessary, is the entryway wide enough for a wheelchair/walker?", 9),
    ("If people need support, are there handrails along the hall on both sides and are they reinforced?", 9),

    ("Is there a light switch at both ends of the hall?", 10),
    ("If necessary, are halls wide enough for a wheelchair/walker?", 10),
    ("Are halls free of clutter and other tripping obstacles?", 10),
    ("Do all doors open easily?", 10),
    ("Are thresholds less than one inch?", 10),
    ("Are latches and door handles in good condition and easy to use?", 10),
    ("If someone is having trouble turning a doorknob, are there lever handles?", 10),

    ("Stair type and location?", 11),
    ("Do stairs have sturdy rails on both sides that are securely fastened?", 11),
    ("Do rails continue onto the landings?", 11),
    ("Are the stair treads sturdy, not deteriorating or broken?", 11),
    ("Are edges of stair treads clearly visible (no dark, busy patterns)?", 11),
    ("Are stair pads in good repair (tacked down, in one piece)?", 11),
    ("(If carpeted) Is carpet securely attached, not worn or frayed?", 11),
    ("Are top and bottom steps highlighted?", 11),
    ("Are stairs free of clutter?", 11),
    ("If stairs have a low, overhanging beam that people could bump their heads on, has it been padded?", 11),
    ("Are stairs and landings well lit, with light switches at both top and bottom?", 11),

    ("Is the lighting adequate?", 12),
    ("Is there a  light switch at the entrance to the room?  Is it automatic?", 12),
    ("Is there a clear, unobstructed path through the room (no clutter, cords, wires, baskets or other things to trip over)?", 12),
    ("Are thresholds minimal?", 12),
    ("What type of surface is the flooring?", 12),
    ("Are plastic runners/carpet protectors tacked down (not folded or turned up at edges)?", 12),
    ("Are there rugs or mats 2'X4' and are they anti-skid or gel pads?", 12),
    ("Is tile/carpet/linoleum free of chips or tears, and slip resistant?", 12),
    ("Are bare wood floors slip resistant?", 12),
    ("Is there at least one comfortable chair people can get in and out of safely and easily?", 12),
    ("Is furniture stable?", 12),
    ("Is there a 36” travel route around furniture?", 12),
    ("Are shades and blinds easy to open and securely attached?", 12),

    ("Is lighting adequate?", 13),
    ("Is there a light switch at the entrance to the room?", 13),
    ("Is there a clear, unobstructed path through the room (no clutter, cords, wires, baskets or other things to trip over)?", 13),
    ("Are thresholds minimum 1/4in or 1/2in beveled?", 13),
    ("What type of surface is the flooring?", 13),
    ("Are carpets in good condition (not frayed or turned up, torn, or with worn spots that someone could trip over)?", 13),
    ("Is the sitting area carpeted?", 13),
    ("Do throw rugs have anti-skid backing and no upturned corners?", 13),
    ("Is there at least one comfortable armchair?", 13),
    ("Is there a reading table/lamp next to the chair?", 13),
    ("Is there an area rug under the cocktail table?", 13),
    ("Is there a 36” travel route around furniture?", 13),
    ("Are there child proof plugs in all unused outlets?", 13),
    ("Is there color contrast?", 13),

    ("Is lighting adequate? Direct/indirect/task?", 14),
    ("Is there a light switch at the entrance to the room?", 14),
    ("Are thresholds minimal?", 14),
    ("Is there a clear unobstructed path to both sides of the bed? (36” min)", 14),
    ("Flooring surface/tile/ carpet/wood?", 14),
    ("Is carpet in good condition (not frayed or turned up, torn, or with worn spots that someone could trip over)?", 14),
    ("Is there a sitting area? Comfortable chair/bench?", 14),
    ("Do throw rugs have anti-skid backing and no upturned corners?", 14),
    ("Is there at least one comfortable armchair?", 14),
    ("Is there a reading table/lamp next to the bed?", 14),
    ("Is there a TV or electronics in the room?", 14),
    ("Is there medical equipment in the room? CPAP machine?", 14),
    ("Are there adequate outlets near the bed?", 14),
    ("Is there wayfinding from the bed to the bathroom?", 14);

    -- ("", 15),
    -- ("", 15),
    -- ("", 15),
    -- ("", 15),
    -- ("", 15),
    -- ("", 15),
    -- ("", 15),
    -- ("", 15),

    -- ("", 16),
    -- ("", 16),
    -- ("", 16),
    -- ("", 16),
    -- ("", 16),
    -- ("", 16),

    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),
    -- ("", 17),

    -- ("", 18),
    -- ("", 18),
    -- ("", 18),
    -- ("", 18),
    -- ("", 18),
    -- ("", 18),
    -- ("", 18),
    -- ("", 18),
    -- ("", 18),
    -- ("", 18),
    -- ("", 18),
    -- ("", 18),
    -- ("", 18),
    -- ("", 18),

    -- ("", 19),
    -- ("", 19),
    -- ("", 19),
    -- ("", 19),
    -- ("", 19),
    -- ("", 19),
    -- ("", 19),
    -- ("", 19),

    -- ("", 20),
    -- ("", 20),
    -- ("", 20),
    -- ("", 20),
    -- ("", 20),
    -- ("", 20),

    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),
    -- ("", 21),

    -- ("", 22),
    -- ("", 22),
    -- ("", 22),
    -- ("", 22),
    -- ("", 22),
    -- ("", 22),
    -- ("", 22),
    -- ("", 22),
    -- ("", 22),
    -- ("", 22),
    -- ("", 22),
    -- ("", 22),
    -- ("", 22),
    -- ("", 22),

    -- ("", 23),
    -- ("", 23),
    -- ("", 23),
    -- ("", 23),
    -- ("", 23),
    -- ("", 23),
    -- ("", 23),
    -- ("", 23),

    -- ("", 24),
    -- ("", 24),
    -- ("", 24),
    -- ("", 24),
    -- ("", 24),
    -- ("", 24),

    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),
    -- ("", 25),

    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),
    -- ("", 26),

    -- ("", 27),
    -- ("", 27),
    -- ("", 27),
    -- ("", 27),
    -- ("", 27),
    -- ("", 27),
    -- ("", 27),
    -- ("", 27),
    -- ("", 27),
    -- ("", 27),

    -- ("", 28),
    -- ("", 28),
    -- ("", 28),
    -- ("", 28),
    -- ("", 28),

    -- ("", 29),
    -- ("", 29),
    -- ("", 29),
    -- ("", 29),
    -- ("", 29),
    -- ("", 29),
    -- ("", 29),
    -- ("", 29),
    -- ("", 29),
    -- ("", 29),

    -- ("", 30),
    -- ("", 30),
    -- ("", 30),
    -- ("", 30),

    -- ("", 31),
    -- ("", 31),
    -- ("", 31),
    -- ("", 31),
    -- ("", 31),
    -- ("", 31),

    -- ("", 32),
    -- ("", 32),
    -- ("", 32),
    -- ("", 32),
    -- ("", 32),
    -- ("", 32),

    -- ("", 33),
    -- ("", 33),
    -- ("", 33),
    -- ("", 33),
    -- ("", 33),
    -- ("", 33),
    -- ("", 33),
    -- ("", 33),
    -- ("", 33),

    -- ("", 34),
    -- ("", 34),
    -- ("", 34),
    -- ("", 34),
    -- ("", 34),
    -- ("", 34),
    -- ("", 34),

    -- ("", 35),
    -- ("", 35),
    -- ("", 35),
    -- ("", 35),
    -- ("", 35),
    -- ("", 35),
    -- ("", 35),
    -- ("", 35),
    -- ("", 35),

    -- ("", 36),
    -- ("", 36),
    -- ("", 36),
    -- ("", 36),
    -- ("", 36),
    -- ("", 36),
    -- ("", 36),
    -- ("", 36),
    -- ("", 36),
    -- ("", 36),
    -- ("", 36),
    -- ("", 36),
    -- ("", 36),
    -- ("", 36),
    -- ("", 36),
    -- ("", 36),
    -- ("", 36),
    -- ("", 36),
    -- ("", 36),
    -- ("", 36),
    -- ("", 36)